### ISSUE TITLE
Issue with lower zoom levels

### ISSUE THREAD

**Issue by nerik** [hotosm/osm-analytics-cruncher#13]
Hello,

I can't get the cruncher to generate aggregated tiles below zoom level 12. 
Using the `notippecanoe` branch, the cruncher will only produce non-aggregated tiles at z13, and aggregated tiles at zoom level 12. This can be seen by converting the mbtiles files to PBF tiles, which only produces tile folders at z 13 and 12, and the client gets 404s when trying to fetch tiles under z12.
During crunching, temporary out.[$i].mbtiles all weigh 20kb below z12 before being merged, which is the weight of the empty mbtiles file. It's also worth noting that the chunks produced by tilereduce in downscale.js are not empty (around 70kb each). Could there be something going wrong with the final merging of the chunks?

I will investigate further but I wanted to make sure I'm not missing anything obvious first.

Note: I'm working on a country extract, not the whole planet file (Benin in my case)

**Comment by nerik** [comment]
@tyrasd I'm opening an issue but you might prefer a more direct channel of communication like the Gitter room - let me know.

**Comment by tyrasd** [comment]
this has already been solved
